[game]
max_mistakes = 5
mask_char = '_'
default_language = 'ru'
default_difficulty = 'easy'

[game.alphabets]
ru = 'йцукенгшщзхъфывапролджэячсмитьбюё'
en = 'qwertyuiopasdfghjklzxcvbnm'

[locale]
ru = 'src/hangman/configs/locales/ru.toml'
en = 'src/hangman/configs/locales/en.toml'

[difficulty.ru]
easy = 'src/hangman/configs/data/ru/easy.txt'
medium = 'src/hangman/configs/data/ru/medium.txt'
hard = 'src/hangman/configs/data/ru/hard.txt'

[difficulty.en]
easy = 'src/hangman/configs/data/en/easy.txt'
medium = 'src/hangman/configs/data/en/medium.txt'
hard = 'src/hangman/configs/data/en/hard.txt'
